# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-28 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_auto_20180629_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='businessunit',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='业务线'),
        ),
        migrations.AlterField(
            model_name='contract',
            name='name',
            field=models.CharField(max_length=128, verbose_name='合同名称'),
        ),
        migrations.AlterField(
            model_name='idc',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='机房名称'),
        ),
        migrations.AlterField(
            model_name='manufacturer',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='厂商名称'),
        ),
        migrations.AlterField(
            model_name='nic',
            name='name',
            field=models.CharField(blank=True, max_length=128, null=True, verbose_name='网卡名称'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='标签名'),
        ),
    ]
